export const user = {
	INTIATE_LOGIN: "USER:INTIATE LOGIN",
	LOGIN_SUCCESS: "USER:LOGIN SUCCESS",
	LOGIN_FAILURE: "USER:LOGIN FAILURE",
	INTIATE_LOGOUT: "USER:INTIATE LOGOUT",
	LOGOUT_SUCCESS: "USER:LOGOUT SUCCESS",
	LOGOUT_FAILURE: "USER:LOGOUT FAILURE",
	NEW_SUBSCRIPTION: "USER:NEW SUBSCRIPTION"
}
export const order = {
	NEW_ORDER: "ORDER:NEW ORDER",
	CHANGE_ORDER_TYPE: "ORDER:CHANGE ORDER TYPE",
	NEW_SUBSCRIPTION: "ORDER:NEW SUBSCRIPTION",
}